README.md, sunsynk/definitions.py
Hi.
I have found and used this sensor in Jlopez's implementation to interrogate the inverter through the wifi connection. It is uploaded to github and the file with the specification is this
https://github.com/jlopez77/DeyeInverter/blob/main/DYRealTime.txt
the values that the sensor can have are 1 and 0
{
"titleZH": "并网状态",
"titleEN": "Grid-connected Status",
"registers": ["0x00C2"],
"interactionType": 2,
"parserRule": 1,
"optionRanges": [
{
"key": 0,
"value": "Off-Grid"
},
{
"key": 1,
"value": "On-Grid"
}
],
"ratio": 1,
"unit": ""
},
I don't know if this is the best type of sensor.
It works in turbo-energy and deye inverters.
I don't know python but I think the syntax is something like this.
Regards.
=> Added sensor

hass-addon-sunsynk-dev/CHANGELOG.md, hass-addon-sunsynk-dev/Dockerfile, hass-addon-sunsynk-dev/config.yaml, hass-addon-sunsynk-dev/filter.py, hass-addon-sunsynk-dev/run.py, sunsynk/__init__.py, sunsynk/definitions.py, sunsynk/sensor.py, tests/sunsynk/test_sensor.py
This is the second PR addressing #37.
A `SelectRWSensor` has been introduced which supports an `options` dictionary of register value to display value pairs. This sensor is then used by the dev add-on to create a Home Assistant [MQTT Select](https://www.home-assistant.io/integrations/select.mqtt/).
`RWSensor` also gained come common writable sensor functionality through the `update_reg_value` method which has the common steps to update the register value of the sensor. Subclasses merely need to map an incoming `value` to a register value. Any of these methods can be renamed if needed.
`NumberRWSensor` was also enhanced to deal with `factor` and to validate the incoming `value` against `min_value` and `max_value` when creating a register value.
=> Added SelectRWSensor and priority_mode

hass-addon-sunsynk-dev/CHANGELOG.md, hass-addon-sunsynk-dev/Dockerfile, hass-addon-sunsynk-dev/config.yaml, hass-addon-sunsynk-dev/mqtt.py, hass-addon-sunsynk-dev/run.py, sunsynk/__init__.py, sunsynk/definitions.py, sunsynk/sensor.py, tests/hass-addon-sunsynk-dev/test_mqtt.py, tests/sunsynk/test_sensor.py
This PR builds on the work done in #37 to allow for updating of HASS auto discovery info if a sensor, upon which other sensors depend for their min/max values, changes.
The changes here solve for two issues:
1. If the user of the add-on has added a sensor which depends on another sensor for the min/max values but the user has not added the latter sensor, it automatically gets added as a hidden sensor so that its value can be read in the main loop and the former sensor's HASS discovery info can be updated.
2. If the user walks over to the inverter and changes the sensor value, or the value is changed via the Home Assistant UI (if the sensor is a subclass of `RWSensor`), the change is picked up by the add-on and the HASS discovery info is updated.
Furthermore, the writable battery capacity …
=> Update HASS auto discovery info when sensor values change & add RWSensor icons

hass-addon-sunsynk-dev/CHANGELOG.md, hass-addon-sunsynk-dev/Dockerfile, hass-addon-sunsynk-dev/config.yaml, hass-addon-sunsynk-dev/run.py, sunsynk/__init__.py, sunsynk/definitions.py, sunsynk/sensor.py, tests/sunsynk/test_sensor.py
Resolves #37 
This is the final PR dealing with writable sensors in #37.
The salient changes here are:
- Introduced new `Battery Shutdown voltage`, `Battery Restart voltage` and `Battery Low Voltage` sensors
- Introduced new `Float voltage` sensor upon which the `Prog1-6 Voltage` sensors depend for their `max` value
- Made `Prog1-6 Charge` and `Prog1-6 Voltage` sensors writable
- Made `Equalization voltage` and `Absorption voltage` writable
- Made `Battery Shutdown Capacity`, `Battery Restart Capacity` and `Battery Low Capacity` writable
- Corrected `Prog1-6 Voltage` factor to be 0.01 (this was previously 0.1 which was incorrect)
If the `definitions.py` file can be formatted better, please do let me know.
My one wish from the Home Assistant [MQTT Number …
=> More writable sensors

hass-addon-sunsynk-dev/CHANGELOG.md, hass-addon-sunsynk-dev/DOCS.md, hass-addon-sunsynk-dev/config.yaml, hass-addon-sunsynk-dev/mqtt.py, hass-addon-sunsynk-dev/options.py, hass-addon-sunsynk-dev/run.py
As part of #37 the `NumberRWSensor` was introduced which mapped to the Home Assistant [MQTT Number Integration](https://www.home-assistant.io/integrations/number.mqtt/) entity. At the time, one could not set the `mode` of this entity so this resulted in the `mode` being `auto` for all `NumberRWSensor`s and nearly all of them got displayed as sliders. As of Home Assistant 2022.9.0, `mode` [can be customised](https://github.com/home-assistant/core/issues/77455) and this PR allows for the `mode` to be customised for `NumberRWSensor`s via an option in the add-on.
Before:
After (if setting the `mode` to `box`):
Note: If users do not have HA 2022.9.0, the `mode` field is ignored, therefore this is not a breaking change.
=> Allow NumberEntity mode to be customized

hass-addon-sunsynk-dev/CHANGELOG.md, hass-addon-sunsynk-dev/DOCS.md, hass-addon-sunsynk-dev/Dockerfile, hass-addon-sunsynk-dev/config.yaml, hass-addon-sunsynk-dev/filter.py, hass-addon-sunsynk-dev/run.py, sunsynk/__init__.py, sunsynk/definitions.py, sunsynk/sensors.py, sunsynk/usunsynk.py, tests/hass-addon-sunsynk-dev/test_filter.py, tests/sunsynk/test_sensors.py, tests/sunsynk/test_sunsynk.py
- Add usunsynk timeouts for #60
- Added 2 test sensors for #75
- essential_abs_power
- essential_l2_power
- Removed deprecated `PROFILES` from the docs
=> Essential power test sensors & timeouts

sunsynk/helpers.py, sunsynk/rwsensors.py, tests/sunsynk/test_helpers.py, tests/sunsynk/test_rwsensors.py
Fixes #145 and allow reading & writing negative NumberRWSensor (for single register sensors)
```python
NumberRWSensor(206, "Grid Trickle Feed", WATT, -1, min=-500, max=500)
```
=> Signed NumberRWSensor

www/docs/guide/standalone-deployment.md
This PR updates the documentation around the stand-alone deployment options.
As discussed in issue #183 - there are now pre-built docker images that users can utilise to build a sunsynk-multi container. I have updated the docs to reflect these options and have included some docker CLI commands too. The pre-built images make it a viable option in building docker containers. 
I have also updated some minor grammar on the page. 
Happy to address anything else you may want updated @kellerza, while I'm kicking about in here. :)
=> Update standalone deployment docs

src/sunsynk/definitions.py
Allows the enabling / disabling of the ability to sell excess solar. Users may want to control this option, as when enabled, the system is known to draw 40w at all times. The scenario here is to turn it off when solar is not expected to produce, and turn it back on when solar is producing.
=> Added Solar Export configuration option

hass-addon-sunsynk-edge/config.yaml, src/ha_addon_sunsynk_multi/sensor_options.py, src/sunsynk/definitions3phhv.py, www/docs/guide/tested-inverters.md, www/docs/reference/definitions.md, www/docs/reference/multi-options.md
This is tested and working with Deye 20kw 3phase HV inverter(SUN-20K-SG01-HP3-EU-AM2).
=> 3 phase high voltage inverter support

src/sunsynk/definitions3ph.py
Deye 12kW LV model(SUN-12K-SG04LP3-EU) has 240A battery dis(charge) current.
=> Increase max (dis)charge current

src/sunsynk/definitions3phhv.py, src/tests/sunsynk/migration/old_hv.py, src/tests/sunsynk/migration/old_lv.py
Use correct sensor type to get correct value. Requires offset like other temperature registers.
=> Fix battery temperature sensor

src/ha_addon_sunsynk_multi/sensor_options.py
I made logic error when implementing 3PH HV support. Now 3PH LV gets both 3PH LV and 1PH definitions applied.
Currently:
```
sunsynk-1  | 08:58:17 INFO    Using three phase sensor definitions.
sunsynk-1  | 08:58:17 INFO    Using Single phase sensor definitions.
```
With the patch:
```
sunsynk-1  | 10:11:11 INFO    Using three phase sensor definitions.
```
=> fix definition selection logic introduced when implementing hv support

hass-addon-sunsynk-multi/Dockerfile, setup.cfg
pysolarmanv5 3.0.2 fixes the hanging issue for me.
=> fix hanging when using solarman driver

src/sunsynk/definitions3ph.py, src/sunsynk/definitions3phhv.py
Older firmwares on LV inverters and HV inverter firmwares support negative zero export values. Using negative value injects small ammout to network instead of pulling from network.
=> Negative zero export

hass-addon-sunsynk-multi/README.md, hass-addon-sunsynk-multi/config.yaml, src/ha_addon_sunsynk_multi/options.py, src/sunsynk/__init__.py, www/docs/guide/standalone-deployment.md
Added support of env vars for docker image
=> Add env vars support to options

.github/workflows/deploy-multi-mp.yml
Making the GitHub Actions workflow build a multi-platform image would make standalone deployments much easier to achieve as you use the same image url for all platforms. This has been tested by myself and you can see the results bellow.
Workflow: https://github.com/maslyankov/sunsynk/actions/workflows/deploy-multi-mp.yml
Resulting image/package: https://github.com/maslyankov/sunsynk/pkgs/container/hass-addon-sunsynk-multi
This change would also require docs changes, but I will get to that if there is interest to merge it.
I am currently using the build image like this, same can be used on all platforms:
compose.yml
```
services:
sunsynk-multi:
image: ghcr.io/maslyankov/hass-addon-sunsynk-multi:main
restart: unless-stopped
volumes:
- ./site_data/sunsynk/options.yaml:/data/options.yaml …
```
=> Add multiplatform deployment

.github/workflows/deploy-multi-mp.yml, www/docs/guide/standalone-deployment.md
**Fixes and Enhancements:**
- Resolved issues with image tagging across different platforms.
- Streamlined the tagging process to support all platforms while maintaining backwards compatibility.
**Documentation Update:**
- Added comprehensive documentation for standalone deployment of the `hass-addon-sunsynk-multi` service using Docker Compose and Docker CLI.
- Provided detailed examples for local Docker builds and pre-built images for various architectures (amd64, aarch64, armv7).
- Documented instructions for running the addon alongside `mbusd` on Raspberry Pi and other hosts without requiring Home Assistant.
**Cleanups:**
- Removed unnecessary steps and streamlined the instructions for easier deployment.
This PR ensures smoother multi-platform support and provides clarity for users …
=> Fix multi platform build and add docs

src/sunsynk/definitions/three_phase_common.py
Some sensors for the Deye/Sunsynk 3-phae inverter where corrected and added. 
* Inverter L1-L3 voltage
* Load frequency
Thx. for reviewing.
=> Deye/Sunsynk 3-phae inverter sensors for inverter and load added

hass-addon-sunsynk-multi/Dockerfile.local, src/ha_addon_sunsynk_multi/a_inverter.py, src/ha_addon_sunsynk_multi/sensor_options.py, src/sunsynk/definitions/__init__.py, src/sunsynk/definitions/single_phase.py, src/sunsynk/definitions/three_phase_common.py, src/sunsynk/definitions/three_phase_hv.py, src/sunsynk/sensors.py, src/tests/ha_addon_sunsynk_multi/test_sensor_callback.py, src/tests/ha_addon_sunsynk_multi/test_sensor_options.py, src/tests/ha_addon_sunsynk_multi/test_state.py
Continue on #377 & hopefully fixing #374
There are only a single set of sensor options. So, the order that we add these seem important. Deps can be visible if configured on all/1st inverter.
Startup sensors are used to read limited info from the inverter and make sure that the wiring/configuration is correct. By far the most issues on the repo is related to connectivity, so don't want to change this.
- In line with #377 - the addon now reads all sensors after the serial number is verified
=> Sensor options

src/sunsynk/definitions/single_phase.py, src/sunsynk/definitions/three_phase_common.py
New name changed from Switch "Inverter Power" to "Inverter enabled" to avoid override.
=> Deye 3phase power switch renamed to Inverter enabled

src/sunsynk/helpers.py, src/sunsynk/rwsensors.py, src/sunsynk/sensors.py, src/sunsynk/state.py, src/tests/sunsynk/test_helpers.py, src/tests/sunsynk/test_rwsensors.py
- Added `make_32bit` to convert two 16-bit values into a 32-bit integer.
- Introduced `split_to_16bit` to split a 32-bit integer into two 16-bit values.
- Updated `signed` function to handle struct packing for signed integers.
- Modified `NumberRWSensor` to utilize `split_to_16bit` for handling two 16-bit registers.
- Refactored `reg_to_value` in `Sensor` class to use `make_32bit` for combining register values.
Related PR & issues that arised from it:
- https://github.com/kellerza/sunsynk/pull/391#issuecomment-2599665488
- https://github.com/kellerza/sunsynk/pull/391#issuecomment-2599698838
- https://github.com/kellerza/sunsynk/issues/398
Using struct for handling signed integers (especially when merging registers) is better for several key reasons:
1. **Proper Two's Complement …
=> Enhance helper functions for register value conversions

www/docs/guide/tested-inverters.md
Tested working on my SYNK-7K-SG05LP1 and 2x Sunsynk W5.32 batteries using a CAN/RS485 splitter in the port used by the BMS (top right) and a USR-W630.
=> Add tested inverter Sunsynk 7kW (SYNK-7K-SG05LP1)
